# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_clip <- function(x, a, b) {
    .Call('_stools_rcpp_clip', PACKAGE = 'stools', x, a, b)
}

