# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clip vector between numbers a and b
#'
#' @param x Input vector
#' @param a Minumum value
#' @param b Maximum value
#' @export
rcpp_clip <- function(x, a, b) {
    .Call('_stools_rcpp_clip', PACKAGE = 'stools', x, a, b)
}

